name: npm test
on: 
  workflow_dispatch:
  push:
               
jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4.2.2  
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: run test
        shell: bash
        run: |
          npm install
          npm test
